version: '3.8'

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "1323:1323"
    env_file:
      - .env

  vite-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3002:3002"
    command: sh -c "npm install && concurrently \"npm run dev -- --no-open --host 0.0.0.0\" \"npm run watch-css\""
