name: Weekly Snippets Discussion Creation
on:
  workflow_dispatch:
  schedule:
  - cron: 0 8 * * 2  # Every Tuesday at 08:00 UTC

jobs:
  weekly_discussion:    
    name: Create new discussion
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/github-script@v3
      with:
        # TODO Change this to a GITHUB TOKEN (not PAT) once the Discussions API is publicly available
        # github-token: ${{ secrets.GITHUB_TOKEN }}
        github-token: ${{secrets.PAT_FOR_DISCUSSIONS_API}}
        script: |
          // Get date for next weekday ordinal
          // (0 = sunday, 1 = monday, 2 = tuesday, 3 = wednesday, 4 = thursday, 5 = friday, 6 = saturday)
          function nextDay(targetdayofweek) {
              var now = new Date();
              var nextDate = new Date();
              console.log("Now = " + now);
              console.log("Now as ISO = " + now.toISOString());
              var todaysday = now.getUTCDay();
              console.log("Todays day = " + todaysday);
              var delta = targetdayofweek + (7-todaysday) % 7;
              console.log("Delta = " + delta);
              nextDate.setUTCDate(now.getUTCDate() + delta);
              console.log("New day = " + nextDate);
              console.log("New day as ISO = " + nextDate.toISOString());
              return nextDate;
          }
          // Add specified number of days to today's UTC day of the month
          function addDays(daysToAdd) {
              var now = new Date();
              var nextDate = new Date();
              console.log("Now = " + now);
              console.log("Now as ISO = " + now.toISOString());
              var todaysday = now.getUTCDay();
              console.log("Todays day = " + todaysday);
              nextDate.setUTCDate(now.getUTCDate() + daysToAdd);
              console.log("New day = " + nextDate);
              console.log("New day as ISO = " + nextDate.toISOString());
              return nextDate;
          }
          //const title = `Weekly Snippets for ${nextDay(9).toISOString().split('T')[0]}`;
          const title = `Weekly Snippets for ${addDays(7).toISOString().split('T')[0]}`;
          console.log(title);

          const body = `
          1. Snippets from the team should following the format of [this template](https://github.com/matthewmccullough/human-interaction-templates/blob/master/weekly-snippets.md).
          2. If you don't have a lot, that's fine. Even one bullet point is helpful.
          3. Link out to resources and issues more than you write.
          4. @matthewmccullough ships his snippets and excerpts of these to leadership each Tuesday evening around 19:00 Pacific Time.
          `;
          const repository_id = "MDEwOlJlcG9zaXRvcnkzNjY1NTk1NjE=";
          const category_id = "MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyOTIzMzcy"; // Snippets

          const query = `
            mutation {
                createDiscussion(input:{repositoryId: "${repository_id}", categoryId: "${category_id}", title: "${title}", body: "${body}"}) {
                  discussion { id, title }
                }
            }`;
          
          const {createDiscussion: { discussion }} = await github.graphql(
            query, {
              headers: {
                "GraphQL-Features": "discussions_api",
              },
          });
          console.log(`Created discussion with id ${discussion.id}`);
